# Generated by Django 4.2.11 on 2026-05-18 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=50, unique=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('captured', 'Captured')], max_length=20)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('platform_fee_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('payment_method', models.CharField(max_length=20)),
                ('installments', models.IntegerField(default=1)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['idempotency_key', 'created_at'], name='api_payment_idempot_0aadfc_idx')],
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outboxevents', to='api.payment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgerentries', to='api.payment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
